service: page-renderer

provider:
  name: aws
  stage: dev
  region: eu-west-3
  runtime: nodejs14.x
  memorySize: 1536
  timeout: 30

functions:
  render:
    handler: render.handler
    url:
      authorizer: aws_iam

package:
  artifact: ./package.zip

plugins:
  - serverless-hooks-plugin

custom:
  hooks:
    package:initialize:
      - yarn package
